  steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fuel-management-backend-2:$COMMIT_SHA', '--build-arg', 'GITHUB_TOKEN=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' '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fuel-management-backend-2:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'fuel-management-backend-2'
    - '--image'
    - 'gcr.io/$PROJECT_ID/fuel-management-backend-2:$COMMIT_SHA'
    - '--region'
    - 'asia-southeast1'

  images:
  - 'gcr.io/$PROJECT_ID/fuel-management-backend-2:$COMMIT_SHA'