services:
  # app:
  #   container_name: fuel-management-backend
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     args:
  #       - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   develop:
  #     watch:
  #       - action: rebuild
  #         files:
  #           - ./**/*.go
  #           - ./go.mod
  #           - ./go.sum
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - fuel-management

  postgres:
    container_name: fuel-management-postgres
    image: postgres:16-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Bangkok
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - fuel-management-postgres-data:/var/lib/postgresql/data
    networks:
      - fuel-management

networks:
  fuel-management:

volumes:
  fuel-management-postgres-data:
