server:
  port: "8080"

database:
  use: "postgres"
  postgres:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "postgres"
    dbname: "fuel"
    sslmode: "disable"
  sqlite:
    file_path: "./test.db"

logger:
  is_production_env: false
