server:
  port: "8080"

database:
  postgres:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "postgres"
    dbname: "fuel"
    sslmode: "disable"
  sqlite:
    filePath: "./test.db"

logger:
  isProductionEnv: false
  maskingFields:
    - firstName
    - lastName
  removingFields:
    - firstName
    - lastName
