server:
  port: "8080"

database:
  postgres:
    host: "db.kuzouiwlxsjbmzvloggy.supabase.co"
    port: "5432"
    username: "postgres"
    password: "Csp_postgresql_3695"
    dbname: "postgres"
    sslmode: ""
  sqlite:
    file_path: "./test.db"

logger:
  is_production_env: false
  masking_fields:
    - firstName
    - lastName
  removing_fields:
    - firstName
    - lastName
